apiVersion: networking.istio.io/v1beta1
kind: Gateway
annotations:
  argocd.argoproj.io/compare-options: IgnoreExtra
metadata:
  name: server-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts: 
    - "*"