apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: server-gateway
  annotations:
    argocd.argoproj.io/compare-options: IgnoreForeignExtraneous
    argocd.argoproj.io/sync-options: PruneForeign=false
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts: 
    - "*"